USE  milaap;
SELECT d.name, COUNT(e.id)
FROM employee as e
LEFT JOIN department as d
ON e.DEPT_ID = d.ID
GROUP BY  d.name
ORDER BY COUNT(e.id) DESC, d.name ASC
USE milaap:
SELECT STUDENT.ID , STUDENT.NAME
FROM STUDENT
ORDER BY STUDENT.SCORE DESC, STUDENT.ID ASC
LIMIT 3
USE  milaap;
SELECT CUSTOMER.ID, CUSTOMER.NAME
FROM CUSTOMER
ORDER BY CUSTOMER.NAME DESC, CUSTOMER.ID ASC
